const DB_NAME="sonora_db",DB_VERSION=1,STORE="state";
const defaults={songs:[],playlists:[{id:"starter",name:"My First Mix",description:"A little collection of songs I love.",mood:"Dreamy",color:"#d8a7ff",cover:null,songIds:[]}],favorites:[],currentSongId:null,queue:[],queueIndex:0,shuffle:false,repeat:false,theme:"dark"};
let state=structuredClone(defaults),audio=document.getElementById("audio"),urls=new Map();

const uid=p=>p+"_"+(crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random());
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmt=s=>!isFinite(s)?"0:00":`${Math.floor(s/60)}:${Math.floor(s%60).toString().padStart(2,"0")}`;
function db(){return new Promise((res,rej)=>{let r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function load(){let d=await db();return new Promise(res=>{let r=d.transaction(STORE,"readonly").objectStore(STORE).get("state");r.onsuccess=()=>res(r.result||structuredClone(defaults));r.onerror=()=>res(structuredClone(defaults))})}
async function save(){let d=await db();return new Promise((res,rej)=>{let t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(state,"state");t.oncomplete=res;t.onerror=()=>rej(t.error)})}
const song=id=>state.songs.find(s=>s.id===id), playlist=id=>state.playlists.find(p=>p.id===id);
function toast(x){let e=document.createElement("div");e.className="toast";e.textContent=x;document.body.append(e);setTimeout(()=>e.remove(),2200)}
function cover(x,small=false){return `<div class="cover ${small?"small":""}" style="background:${esc(x?.color||"#d8a7ff")}">${x?.cover?`<img src="${esc(x.cover)}" alt="">`:"♪"}</div>`}
function setTheme(){document.body.classList.toggle("light",state.theme==="light");themeBtn.textContent=state.theme==="light"?"☀":"☾"}
function card(p){return `<article class="card" data-pl="${p.id}">${cover(p)}<h3>${esc(p.name)}</h3><p>${p.songIds.length} songs · ${esc(p.mood)}</p></article>`}
function list(ss){return `<div class="song-list">${ss.map((s,i)=>`<div class="song-row"><div class="song-no">${i+1}</div><div class="song-info"><strong>${esc(s.title)}</strong><span>${esc(s.artist)} · ${esc(s.album)}</span></div><div class="row-actions"><button data-play="${s.id}">▶</button><button data-fav="${s.id}">${state.favorites.includes(s.id)?"♥":"♡"}</button></div></div>`).join("")}</div>`}
function render(){
 let v=window.view||"home",q=document.getElementById("searchInput").value.toLowerCase(),root=document.getElementById("view");
 if(v==="home")root.innerHTML=`<div class="hero"><div class="eyebrow">Personal music studio</div><h1>Your music. Your mood. Your world.</h1><p>Build playlists with your own touch, keep your authorized music in one beautiful library, and prepare playlists to share or publish to supported music services.</p><div class="cta"><button class="primary" id="addHero">＋ Add songs</button><button class="secondary" id="newHero">Create a playlist</button></div></div><div class="section-head"><h2>Your playlists</h2><button class="secondary" id="allPl">View all</button></div>${state.playlists.length?`<div class="cards">${state.playlists.map(card).join("")}</div>`:"<div class='empty'>Create your first playlist.</div>"}<div class="section-head"><h2>Recently added</h2></div>${state.songs.length?list([...state.songs].reverse().slice(0,8)):"<div class='empty'>Add your own or authorized audio files.</div>"}`;
 if(v==="library"){let ss=state.songs.filter(s=>`${s.title} ${s.artist} ${s.album}`.toLowerCase().includes(q));root.innerHTML=`<div class="section-head"><div><div class="eyebrow">Library</div><h2>Every song you've added</h2></div><button class="primary" id="addBtn">＋ Add songs</button></div>${ss.length?list(ss):"<div class='empty'>No songs found.</div>"}`}
 if(v==="playlists")root.innerHTML=`<div class="section-head"><div><div class="eyebrow">Collections</div><h2>Your playlists</h2></div><button class="primary" id="newBtn">＋ New playlist</button></div><div class="cards">${state.playlists.map(card).join("")}</div>`;
 if(v==="favorites"){let ss=state.songs.filter(s=>state.favorites.includes(s.id));root.innerHTML=`<div class="section-head"><div><div class="eyebrow">Favorites</div><h2>Songs you love</h2></div></div>${ss.length?list(ss):"<div class='empty'>Favorite songs appear here.</div>"}`}
 bind();
}
function go(v){window.view=v;document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));render()}
function bind(){document.querySelectorAll("[data-pl]").forEach(x=>x.onclick=()=>openPlaylist(x.dataset.pl));document.querySelectorAll("[data-play]").forEach(x=>x.onclick=()=>playQueue([x.dataset.play],0));document.querySelectorAll("[data-fav]").forEach(x=>x.onclick=()=>fav(x.dataset.fav));document.getElementById("addBtn")?.addEventListener("click",()=>audioInput.click());document.getElementById("addHero")?.addEventListener("click",()=>audioInput.click());document.getElementById("newBtn")?.addEventListener("click",()=>playlistModal());document.getElementById("newHero")?.addEventListener("click",()=>playlistModal());document.getElementById("allPl")?.addEventListener("click",()=>go("playlists"))}
function modal(title,body){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close" id="closeM">×</button></div>${body}</div></div>`;closeM.onclick=()=>modalRoot.innerHTML=""}
function fileData(f){return new Promise((r,j)=>{let x=new FileReader();x.onload=()=>r(x.result);x.onerror=j;x.readAsDataURL(f)})}
function playlistModal(p=null){
 let x=p||{name:"",description:"",mood:"Dreamy",color:"#d8a7ff",cover:null};
 modal(p?"Edit playlist":"Create playlist",`<form class="form" id="pf"><div class="cover-editor">${cover(x,true)}<label>Cover image<input id="pc" type="file" accept="image/*"></label></div><label>Name<input id="pn" required value="${esc(x.name)}"></label><label>Description<textarea id="pd">${esc(x.description)}</textarea></label><label>Mood<select id="pm">${["Dreamy","Happy","Chill","Focus","Romantic","Energetic","Melancholy","Nostalgic"].map(m=>`<option ${x.mood===m?"selected":""}>${m}</option>`).join("")}</select></label><label>Accent</label><div class="color-row">${["#d8a7ff","#8de6d1","#ffb7c9","#ffd37d","#8ab4ff","#ff8c8c"].map(c=>`<button type="button" class="color ${x.color===c?"selected":""}" data-c="${c}" style="background:${c}"></button>`).join("")}</div><button class="primary">Save</button></form>`);
 let color=x.color;document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{color=b.dataset.c;document.querySelectorAll("[data-c]").forEach(z=>z.classList.remove("selected"));b.classList.add("selected")});
 pf.onsubmit=async e=>{e.preventDefault();let f=pc.files[0],c=x.cover;if(f)c=await fileData(f);if(p){Object.assign(p,{name:pn.value.trim(),description:pd.value.trim(),mood:pm.value,color,cover:c})}else state.playlists.push({id:uid("pl"),name:pn.value.trim(),description:pd.value.trim(),mood:pm.value,color,cover:c,songIds:[]});await save();modalRoot.innerHTML="";render();toast(p?"Playlist updated":"Playlist created")}
}
function openPlaylist(id){
 let p=playlist(id),ss=p.songIds.map(song).filter(Boolean);window.view="playlist";window.currentPlaylist=id;
 view.innerHTML=`<div class="hero"><div class="eyebrow">${esc(p.mood)} · ${ss.length} songs</div><div style="display:grid;grid-template-columns:180px 1fr;gap:28px;align-items:end;margin-top:15px">${cover(p)}<div><h1>${esc(p.name)}</h1><p>${esc(p.description||"A playlist made in Sonora.")}</p><div class="cta"><button class="primary" id="playPl">▶ Play</button><button class="secondary" id="editPl">Edit</button><button class="secondary" id="addPl">＋ Add songs</button><button class="secondary" id="releasePl">↗ Release</button></div></div></div></div>${ss.length?list(ss):"<div class='empty'>This playlist is empty.</div>"}`;
 bind();playPl.onclick=()=>playQueue(ss.map(s=>s.id),0);editPl.onclick=()=>playlistModal(p);addPl.onclick=()=>chooseSongs(p);releasePl.onclick=()=>release(p)
}
function chooseSongs(p){let rows=state.songs.map(s=>`<label style="display:block;padding:7px"><input type="checkbox" value="${s.id}" ${p.songIds.includes(s.id)?"checked":""}> ${esc(s.title)} — ${esc(s.artist)}</label>`).join("");modal("Add songs",`<form class="form" id="cf">${rows||"<p class='muted'>Add songs to your library first.</p>"}<button class="primary">Save playlist</button></form>`);cf.onsubmit=async e=>{e.preventDefault();p.songIds=[...cf.querySelectorAll("input:checked")].map(x=>x.value);await save();modalRoot.innerHTML="";openPlaylist(p.id)}}
function release(p){modal("Release playlist",`<div class="form"><p class="muted">These buttons are ready for official OAuth integrations after you create your own developer apps. No fake credentials are included.</p><button class="secondary" onclick="toast('Spotify OAuth setup is required')">🎵 Connect Spotify</button><button class="secondary" onclick="toast('YouTube OAuth setup is required')">▶ Connect YouTube</button><div class="empty">See INTEGRATIONS.md for setup.</div></div>`)}
async function addFiles(fs){let n=0;for(let f of fs){if(!f.type.startsWith("audio/"))continue;state.songs.push({id:uid("song"),title:f.name.replace(/\.[^/.]+$/,""),artist:"Local Artist",album:"My Library",blob:f,addedAt:Date.now()});n++}if(n){await save();toast(`${n} song${n>1?"s":""} added`);render()}}
function url(s){if(!s)return null;if(!urls.has(s.id))urls.set(s.id,URL.createObjectURL(s.blob));return urls.get(s.id)}
function play(id){let s=song(id);if(!s)return;state.currentSongId=id;audio.src=url(s);audio.play().catch(()=>{});playerTitle.textContent=s.title;playerArtist.textContent=`${s.artist} · ${s.album}`;playerFavorite.textContent=state.favorites.includes(id)?"♥":"♡"}
function playQueue(ids,i=0){state.queue=ids;state.queueIndex=i;play(ids[i])}
function next(){if(!state.queue.length)return;if(state.repeat)return play(state.currentSongId);let i=state.shuffle?Math.floor(Math.random()*state.queue.length):(state.queueIndex+1)%state.queue.length;state.queueIndex=i;play(state.queue[i])}
function prev(){if(audio.currentTime>4)return audio.currentTime=0;if(!state.queue.length)return;state.queueIndex=(state.queueIndex-1+state.queue.length)%state.queue.length;play(state.queue[state.queueIndex])}
async function fav(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];await save();render()}
document.querySelectorAll(".nav-item").forEach(x=>x.onclick=()=>go(x.dataset.view));
newPlaylistBtn.onclick=()=>playlistModal();audioInput.onchange=e=>addFiles(e.target.files);searchInput.oninput=()=>{if(window.view==="library")render()};themeBtn.onclick=async()=>{state.theme=state.theme==="dark"?"light":"dark";setTheme();await save()};openSidebar.onclick=()=>document.querySelector(".sidebar").classList.add("open");closeSidebar.onclick=()=>document.querySelector(".sidebar").classList.remove("open");
playBtn.onclick=()=>{if(!state.currentSongId)return toast("Add and play a song first");audio.paused?audio.play():audio.pause()};nextBtn.onclick=next;prevBtn.onclick=prev;shuffleBtn.onclick=()=>{state.shuffle=!state.shuffle;shuffleBtn.style.opacity=state.shuffle?1:.5};repeatBtn.onclick=()=>{state.repeat=!state.repeat;repeatBtn.style.opacity=state.repeat?1:.5};volume.oninput=e=>audio.volume=+e.target.value;progress.oninput=e=>{if(audio.duration)audio.currentTime=+e.target.value/100*audio.duration};playerFavorite.onclick=()=>state.currentSongId&&fav(state.currentSongId);
audio.ontimeupdate=()=>{currentTime.textContent=fmt(audio.currentTime);progress.value=audio.duration?audio.currentTime/audio.duration*100:0};audio.onloadedmetadata=()=>duration.textContent=fmt(audio.duration);audio.onplay=()=>playBtn.textContent="Ⅱ";audio.onpause=()=>playBtn.textContent="▶";audio.onended=next;
(async()=>{state=await load();window.view="home";audio.volume=.8;setTheme();render()})();
